### ISSUE TITLE
Test and migrate Wordpress example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#103]

**Comment by techmaniack** [comment]
I'm working on this.

**Comment by pleia2** [comment]
Thanks for taking this example on, AbdulKarim!

I've noticed there hasn't been a pull request submitted yet, do you need any help, or just need some more time? If you ran into a problem, updating this issue to explain would be a huge help so we can try to assist you.

If something came up and you aren't able to complete updating this example, no problem! Just let us know that so we can assign it to another community member. We'll look forward to working with you next time :)

**Comment by pleia2** [comment]
Interesting, I had a look and you're right! @ryadav88 do you have any feedback here as to what happened to the package, maybe it's not supported or required any longer?

**Comment by ryadav88** [comment]
Dont understand the question here

**Comment by pleia2** [comment]
Whoops, commented on the wrong issue, you can ignore my note about the package not existing :)

**Comment by techmaniack** [comment]
@pleia2 hey I was trying to follow the GCE setup guide last week and got stuck. Will resume working on it this weekend.

**Comment by techmaniack** [comment]
So my DCOS 1.9 cluster is up on GCE but MySQL service won't start. The marathon-lb service is running fine. The DCOS dashboard is showing no signs of error and everything is green. Resource allocation is not an issue.

I have followed the 1.8 Wordpress guide.

```
mysql service options:
{
  "service": {
    "name": "mysql"
  },
  "database": {
    "name": "wordpress",
    "username": "wordpress",
    "password": "password",
    "root_password": "wordpress"
  },
  "networking": {
    "port": 3306,
    "host_mode": true
  }
}
```

The master logs show this 

> May 07 07:34:47 master0 java[3103]: * Start(App(/mysql, image="mysql:5.7.12"List())), instances=0)
> May 07 07:34:47 master0 java[3103]: * Scale(App(/mysql, image="mysql:5.7.12"List())), instances=1)
> May 07 07:34:47 master0 java[3103]: * Start(App(/mysql, image="mysql:5.7.12"List())), instances=0)
> May 07 07:34:47 master0 java[3103]: * Scale(App(/mysql, image="mysql:5.7.12"List())), instances=1)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,593] INFO  Adding health check for app [/mysql] and version [2017-05-07T07:34:47.537Z]: [MarathonTcpHealthCheck(300 seconds,60 seconds,20 seconds,3,None,Some(3306))] (mesosphere.marathon.core.health.impl.MarathonHealthCheckManager:marathon-akka.actor.default-dispatcher-168)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,594] INFO  Starting health check actor for app [/mysql] version [2017-05-07T07:34:47.537Z] and healthCheck [MarathonTcpHealthCheck(300 seconds,60 seconds,20 seconds,3,None,Some(3306))] (mesosphere.marathon.core.health.impl.HealthCheckActor:marathon-akka.actor.default-dispatcher-168)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,594] INFO  Starting runSpec /mysql (mesosphere.marathon.SchedulerActions:marathon-akka.actor.default-dispatcher-168)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,595] INFO  Successfully started 0 instances of /mysql (mesosphere.marathon.upgrade.AppStartActor:marathon-akka.actor.default-dispatcher-168)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,597] INFO  Already running 0 instances of /mysql. Not scaling. (mesosphere.marathon.SchedulerActions:ForkJoinPool-2-worker-15)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,602] INFO  Started instanceLaunchActor for /mysql version 2017-05-07T07:34:47.537Z with initial count 1 (mesosphere.marathon.core.launchqueue.impl.TaskLauncherActor:marathon-akka.actor.default-dispatcher-163)
> May 07 07:34:47 master0 java[3103]: [2017-05-07 07:34:47,602] INFO  activating matcher ActorOfferMatcher(Actor[akka://marathon/user/launchQueue/1/6-mysql#-1891068075]). (mesosphere.marathon.core.matcher.manager.impl.OfferMatcherManagerActor:marathon-akka.actor.default-dispatcher-156)
> May 07 07:34:47 master0 java[3103]: * Start(App(/mysql, image="mysql:5.7.12"List())), instances=0)
> May 07 07:34:47 master0 java[3103]: * Scale(App(/mysql, image="mysql:5.7.12"List())), instances=1)

And the UI is stuck on this 

![screen shot 2017-05-07 at 1 10 04 pm](https://cloud.githubusercontent.com/assets/524248/25778804/93565542-3326-11e7-8429-4d6528d35d0b.png)

My DCOS cluster looks like this

![screen shot 2017-05-07 at 1 12 04 pm](https://cloud.githubusercontent.com/assets/524248/25778814/d4ad64ae-3326-11e7-84f7-3a56aa6495ac.png)

I have tried the following so far:
- Destroy the app and recreate
- Try installing mysql from Universe (UI)
- Destroy the cluster and recreate master/agents.
- Try installing other services like redis which failed too!

What could I be doing wrong here?

**Comment by pleia2** [comment]
Hmm, I'm unable to re-create the issue here, MySQL is installing OK for me and I am able to complete the installation of WordPress on 1.9. I'm wondering if it's something else in your DC/OS environment that's conflicting with the setting up of MySQL? (Note: I'm not using GCE, I'm using a cluster on AWS, but I'm hoping that shouldn't change how this behaves)
@ryadav88 - Any thoughts of what other logs they can look at to debug?

**Comment by pleia2** [comment]
Completed by @jejo in #179
