### ISSUE TITLE
Remove colon character from filenames in ceph examples

### ISSUE THREAD

**Issue by ondrej-smola** [dcos/examples#127]
Colon in file names is forbidden and causes a lot of issues on Windows. 
Files are not visible in file explorer, git is unable to work with them.

Files:
ceph/1.9/img/img:configure_secrets_in_exhibitor.png
ceph/1.8/img/img:configure_secrets_in_exhibitor.png

**Comment by pleia2** [comment]
Thanks for the report, I don't see a reason for these files to be named in this way, so I'll go ahead and create a PR.
