### ISSUE TITLE
Add Redis example

### ISSUE THREAD

**Issue by ryadav88** [dcos/examples#15]
Corresponding Universe PR: https://github.com/mesosphere/universe/pull/817

**Comment by mhausenblas** [comment]
What's the diff to https://github.com/dcos/examples/tree/master/1.8/redis?

**Comment by ryadav88** [comment]
@mhausenblas it asks you to download `mrr` to be able to be able to create redis instances. the motivation here is to be able to do that via this new package. I think instead of creating a new example, we can just update the existing one. @joerg84 please chime in.

**Comment by joerg84** [comment]
I will add it to that existing redis example. Basically mrr is very complex if I just want to try running a single redis instance (Demos, tutorials). So there will be two options explained in that example. Single container + mrr.

**Comment by ryadav88** [comment]
closing per https://github.com/dcos/examples/pull/24/
