### ISSUE TITLE
Package [gitlab-runner] not found

### ISSUE THREAD

**Issue by nkhanal0** [dcos/examples#160]
When following the example of `gitlab-runner` and trying to test it with `DCOS 1.9`, It gives an error.
Steps that can be taken to reproduce the issue: 
1. Create an `options.json` with the following content:
`{
  "service": {
    "name": "gitlab-runner-shell"
  },
  "gitlab": {
    "service-name": "gitlab.marathon.mesos",
    "registration-token": "Your_Registration-Token from GitLab"
  },
  "gitlab-runner": {
    "executor": "shell",
    "tag-list": "build-as-docker,build-in-shell",
    "concurrent-builds": 4
  }
}`
2. Run the following code from the terminal:
`dcos package install --options=options.json gitlab-runner`
3. Following is the output:
`Package [gitlab-runner] not found` 
4. Also tried with the following `options.json`: 
`{
  "service": {
    "name": "gitlab-runner-docker"
  },
  "gitlab": {
    "service-name": "gitlab.marathon.mesos",
    "registration-token": "b_EsjLKVyXahggrFzZHr"
  },
  "gitlab-runner": {
    "executor": "docker",
    "tag-list": "build-in-docker,docker",
    "concurrent-builds": 4,
    "docker-default-image": "node:6-wheezy",
    "docker-insecure-registry": "myregistry.mydomain.mytld"
  }
}`
5. It has the same result.

**Comment by judithpatudith** [comment]
Hi! It looks like this package never made it into the universe at all. Closing the issue, and will remove the example shortly. Thanks for reporting it!
