### ISSUE TITLE
Elasticsearch doc references mesos-elasticsearch

### ISSUE THREAD

**Issue by nickbp** [dcos/examples#190]
mesos-elasticsearch isn't DC/OS elasticsearch

Current doc links to these which are unrelated:
- http://mesos-elasticsearch.readthedocs.io/en/latest/
- https://github.com/mesos/elasticsearch

Should probably link to:
- https://docs.mesosphere.com/service-docs/elastic/
- https://github.com/mesosphere/dcos-commons/tree/master/frameworks/elastic

**Comment by nickbp** [comment]
Actually, given the docs linked above, the elasticsearch doc in this repo appears to be a duplicate.

**Comment by judithpatudith** [comment]
@nickbp Hi! Can I close this issue, or does something still need doing? I'm a bit confused about what the Elastisearch doc is duplicating. Thanks!

**Comment by nickbp** [comment]
The following pages link to a separate Mesos Elasticsearch project (not DC/OS Elastic):
- https://github.com/mesos/elasticsearch
- http://mesos-elasticsearch.readthedocs.io/en/latest/

Docs in question:
- https://github.com/dcos/examples/tree/master/elasticsearch/1.8
- https://github.com/dcos/examples/tree/master/elasticsearch/1.9
- https://github.com/dcos/examples/tree/master/elasticsearch/1.10

**Comment by judithpatudith** [comment]
I think that [elasticsearch](http://universe.dcos.io/#/package/elasticsearch/version/latest) is a community contributed package, and not the same as [elastic](http://universe.dcos.io/#/package/elastic/version/latest). This document should be about the former, which looks like it is based on Mesos Elastic.

**Comment by nickbp** [comment]
Would calling the community package "DC/OS Elasticsearch" be confusing when there's a supported `elastic` package?

**Comment by judithpatudith** [comment]
@ryadav88 Thoughts on how to distinguish these things? I know it took me a long time to work out the difference between the elasticsearch and elastic packages, and I'm still a bit confused about why beta-elastic is also still around.
