### ISSUE TITLE
artifactory-lb does not use provided SSL certificate

### ISSUE THREAD

**Issue by Oder70** [dcos/examples#253]
Hi

While installing artifactory-lb from the universe package, we supply the proper certificate and key.
They are fetched correctly, but artifactory-lb does not use them, instead it uses the default "localhost" certificate.
Can't use Artifactory for secure Docker registry on DC/OS.

Regards

**Comment by judithpatudith** [comment]
Hi, @Oder70 thanks for reporting this! I think Artifactory maintains this package, and it looks like you can get in touch with them by emailing soleng-team@jfrog.com. Would you mind sending them the report?

**Comment by Oder70** [comment]
Hi Judith,

JFrog is already aware of that.

We go through it with the following workaround after deploying
artifactory-lb:

docker exec <container-id> cp /mnt/mesos/sandbox/<certfile>
/etc/pki/tls/certs
docker exec <container-id> cp /mnt/mesos/sandbox/<keyfile>
/etc/pki/tls/private
docker exec <container-id> nginx -s reload

Thanks & Regards!
