### ISSUE TITLE
minio - update example for 1.11

### ISSUE THREAD

**Issue by judithpatudith** [dcos/examples#303]
https://github.com/dcos/examples/tree/master/minio

Pick any open and unassigned issue in the list of GitHub issues and assign it to yourself by leaving a comment here in the issue. Then update the example by following these steps:

- [ ] Fork the examples repo on GitHub.
- [ ] On a new branch, make a copy of latest example directory (mostly 1.10 or 1.9) for your package and name it 1.11.
- [ ] Test the example on a DC/OS 1.11 cluster. As you test, replace the old screenshots with new ones and make any necessary corrections to the example.
- [ ] Feel free to also improve the instructions.
- [ ] Add a link to your newly created 1.11 example to the README.md file for your package's directory.
- [ ] Report your results:
  - If the example works out of the box, or you are able to correct it, open a PR with your changes (including the example itself and its addition to the README.md file) and add it to the issue.
  - If you can’t get your example to work, add a detailed description of what went wrong on the issue (you still get stickers!).

When you’re done, email community-team@dcos.io with the following information:
**Subject**: 1.11 Example Testing - [Service Name]
**Body**:
- Your name
- GitHub Issue link
- Your Twitter handle, if you have one
- Community Slack handle if you have one
- Mailing address (for the stickers)

The Community team shepherd will review your PR and either work with you to make modifications or just merge it if it looks good.

**Comment by thakkaryash94** [comment]
I can do this.

**Comment by pleia2** [comment]
Thanks again for working on this!
