### ISSUE TITLE
Test and migrate GeoServer example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#77]

**Comment by gisjedi** [comment]
Required some package updates but it will be shortly be updated.

**Comment by pleia2** [comment]
Great to hear! How is the progress coming on the package updates? Do you have any links to the work you're doing, or need any help from us?

**Comment by gisjedi** [comment]
@pleia2 Should have this done later today. Let you know then. Thanks!

**Comment by gisjedi** [comment]
@pleia2 Should be good to go along with the updates to the Universe in https://github.com/mesosphere/universe/pull/1145

**Comment by pleia2** [comment]
Thanks again! @ryadav88 merged this on the 14th, closing.
