### ISSUE TITLE
Test and migrate GitLab example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#78]

**Comment by matpil** [comment]
I'm working on this.

**Comment by pleia2** [comment]
Thanks for taking this example on!

I've noticed there hasn't been a pull request submitted yet, do you need any help, or just need some more time? If you ran into a problem, updating this issue to explain would be a huge help so we can try to assist you.

If something came up and you aren't able to complete updating this example, no problem! Just let us know that so we can assign it to another community member. We'll look forward to working with you next time :)

**Comment by matpil** [comment]
Hi!
I ran dcos 1.9 with vagrant and I followed the example of the 1.8 version (configured Jenkins, configured marathon-lb, configured gitlab).

Everything seems ok... but RAM is over :(
It looks like 16gb of ram is not enough (and I can't upgrade anymore).

I think I'm about 60% of the sample (I managed to create the project on gitlab with difficulty). :(

**Comment by pleia2** [comment]
Thanks for the update, I'll have a look at the resources required here.

If you are able to complete this, for the PR you can copy (not rename or move) some of the materials from the 1.8 example, but screenshots and some other things may need to be updated. We want to keep the 1.8 example in the repository for folks who are still using the older version.

**Comment by pleia2** [comment]
Update to 1.9 proposed in #183
