### ISSUE TITLE
Test and migrate GitLab Runner example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#79]

**Comment by nkhanal0** [comment]
I'm working on this.

**Comment by nkhanal0** [comment]
It seems like the example has some kind of issue when I try to run `dcos package install --options=options.json gitlab-runner`. This is the output I get: `Package [gitlab-runner] not found`. My `options.json` file has everything mentioned in the example as well as the `registration-token`.

**Comment by pleia2** [comment]
Thanks for looking into this! @ryadav88 do you have any insight to what happened with this package? Removed, unsupported, not needed, or..?

**Comment by ryadav88** [comment]
we merged the example before the package. cc @tobilg 

@nkhanal0 Can I ask you to please pick another example.

**Comment by pleia2** [comment]
This package no longer exists, confirmed with @ryadav88 that it can be closed since we're not making a 1.9 version.

**Comment by tobilg** [comment]
It was not yet merged into the Universe @pleia2

**Comment by ryadav88** [comment]
Thats on me. I asked @pleia2 to close it. We can keep it open until the Universe PR is merged. 
Universe PR: https://github.com/mesosphere/universe/pull/746

**Comment by tobilg** [comment]
Yes, you're right @ryadav88. I'm not sure it ever will/should though. I was just trying to add context to this. You can close it for now. Thanks!

**Comment by judithpatudith** [comment]
Hey team, I'd love to close [this issue](https://github.com/dcos/examples/issues/160) but I'm not sure it was successfully resolved. Thoughts?

**Comment by tobilg** [comment]
The package has never made it in the Universe @judithpatudith, so I guess the issue you referenced can be closed.

**Comment by judithpatudith** [comment]
Thanks!
