### ISSUE TITLE
Test and migrate koding example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#83]

**Comment by PeterDaveHello** [comment]
Let me try this 😄

**Comment by indcoder** [comment]
Will take this one

**Comment by pleia2** [comment]
Thanks again for offering to take this one on. Have you made any progress?

**Comment by pleia2** [comment]
Being worked on in #184 but there are a couple outstanding issues with this package and/or instructions.

**Comment by ryadav88** [comment]
@ohrobin can you take a look?
