### ISSUE TITLE
Test and migrate Neo4J example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#90]

**Comment by neurofoo** [comment]
Anyone working on this? If not, I have neo4j going in 1.9. Everything - so far - worked out of the box. The only issue has been with a javascript driver, but I'm not sure it's 1.9 related yet.

**Comment by pleia2** [comment]
Yes, there's https://github.com/dcos/examples/pull/140 linked here that includes the updates, we'll be reviewing it soon :)

**Comment by gouravshenoy** [comment]
I have closed #140 (as I had created the PR from the master branch in my fork - which did not allow me to create any new PRs for other examples) and created a new #141 for this issue. Thanks!

**Comment by joerg84** [comment]
Resolved
