### ISSUE TITLE
Test and migrate Nginx example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#92]

**Comment by ondrej-smola** [comment]
I am on it

**Comment by pleia2** [comment]
Looks like someone else got to this one first, I think it was before we corrected instructions on how to "assign" the ticket to yourself. I've merged https://github.com/dcos/examples/pull/123 already but will have a look at your updates too in case there's anything we can pull in!

**Comment by pleia2** [comment]
It appears the changes were very similar, so there's nothing else to merge in. We'll be reviewing your other changes soon, so thank you for all your efforts!
